# Generated by Django 4.2.30 on 2026-07-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to='about/', verbose_name='تصویر')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='portfolio.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'تصویر درباره من',
                'verbose_name_plural': 'تصاویر درباره من',
            },
        ),
    ]
