# Generated by Django 4.2.30 on 2026-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='color',
            field=models.CharField(default='#7C3AED', max_length=20),
        ),
    ]
