# Generated by Django 4.2.30 on 2026-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_socialnetwork_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='وضعیت در دسترس بودن (مثل Open to Remote Work یا Seeking PhD)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='سمت یا دانشگاه فعلی (مثل MSc Student at ...)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدرک تحصیلی (مثل Master of Computer Science)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.CharField(blank=True, max_length=300, verbose_name='علایق پژوهشی و تخصصی (با کاما جدا شوند)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه (مناسب زیرعنوان در بخش Hero)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس/لوکیشن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='profile/', verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='متن کامل بیوگرافی (About Me)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name_en',
            field=models.CharField(max_length=100, verbose_name='نام کامل (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name_fa',
            field=models.CharField(max_length=100, verbose_name='نام کامل (فارسی)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume/', verbose_name='فایل رزومه (CV)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تخصص اصلی (مثل Backend Developer)'),
        ),
    ]
