# Generated by Django 4.2.30 on 2026-07-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_availability_status_profile_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.FileField(blank=True, help_text='آیکون مهارت (SVG یا PNG)', null=True, upload_to='skill_icons/'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='icon_image',
            field=models.FileField(blank=True, help_text='تصویر آیکون (پیشنهاد می\u200cشود از فرمت SVG یا PNG شفاف استفاده کنید)', null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_image',
            field=models.FileField(blank=True, help_text='آیکون تکنولوژی (SVG یا PNG)', null=True, upload_to='tech_icons/'),
        ),
    ]
