# Generated by Django 4.2.30 on 2026-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_icon_image_socialnetwork_icon_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon_image',
        ),
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#7C3AED', max_length=20),
        ),
    ]
