# Generated by Django 4.2.30 on 2026-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education_project_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('university', 'University'), ('course', 'Course'), ('bootcamp', 'Bootcamp'), ('certificate', 'Certificate')], default='university', max_length=20),
        ),
    ]
