# Generated by Django 4.2.30 on 2026-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_collaborationinquiry_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'دعوت به همکاری', 'verbose_name_plural': 'دعوت به همکاری ها'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'فیدبک', 'verbose_name_plural': 'فیدبک ها'},
        ),
        migrations.RemoveField(
            model_name='collaborationinquiry',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_read',
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='response',
            field=models.TextField(blank=True, help_text='پاسخی که برای این درخواست ارسال شده یا قرار است ارسال شود'),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='status',
            field=models.CharField(choices=[('unseen', 'دیده نشده'), ('reviewing', 'در حال بررسی'), ('answered', 'بررسی شده و پاسخ داده شده'), ('reviewed_no_response', 'بررسی شده و پاسخ نداده شده')], default='unseen', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, help_text='پاسخی که برای این فیدبک ثبت شده'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('unseen', 'دیده نشده'), ('reviewing', 'در حال بررسی'), ('answered', 'بررسی شده و پاسخ داده شده'), ('reviewed_no_response', 'بررسی شده و پاسخ نداده شده')], default='unseen', max_length=30),
        ),
    ]
